// Copyright 2023 WatsonJay (@WatsonJay)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define ENABLE_COMPILE_KEYCODE

/* 鼠标键配置 */
#define MK_3_SPEED
// #define MK_KINETIC_SPEED
// #define MOUSEKEY_DELAY 8
// #define MOUSEKEY_INTERVAL 5
// #define MOUSEKEY_MOVE_DELTA 8
// #define MOUSEKEY_INITIAL_SPEED 5
// #define MOUSEKEY_BASE_SPEED 600
// #define MOUSEKEY_DECELERATED_SPEED 100
// #define MOUSEKEY_ACCELERATED_SPEED 1500

/* Double tap the side button to enter bootloader */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U

/* I2C 配置 */
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP20
#define I2C1_SCL_PIN GP21

/* SPI pins */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN NO_PIN

/* LCD Configuration */
#define LCD_CS_PIN GP5
#define LCD_DC_PIN GP6
#define LCD_RST_PIN GP7
#define LCD_BL_PIN GP16
#define SPI_DIVISOR 16
#define SPI_MODE    3

#define QP_LVGL_TASK_PERIOD 40

#undef RGBLIGHT_ANIMATIONS
#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_LED_COUNT 10
    #define RGBLED_NUM 10

     /* Enable Framebuffer and keypress effects */
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define RGB_MATRIX_KEYPRESSES

    #define ENABLE_RGB_MATRIX_ALPHAS_MODS
    #define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
    #define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
    #define ENABLE_RGB_MATRIX_BREATHING
    #define ENABLE_RGB_MATRIX_BAND_SAT
    #define ENABLE_RGB_MATRIX_BAND_VAL
    #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
    #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
    #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
    #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
    #define ENABLE_RGB_MATRIX_CYCLE_ALL
    #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
    #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
    #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
    #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
    #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
    #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
    #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
    #define ENABLE_RGB_MATRIX_DUAL_BEACON
    #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
    #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
    #define ENABLE_RGB_MATRIX_RAINDROPS
    #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
    #define ENABLE_RGB_MATRIX_HUE_BREATHING
    #define ENABLE_RGB_MATRIX_HUE_PENDULUM
    #define ENABLE_RGB_MATRIX_HUE_WAVE
    #define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
    #define ENABLE_RGB_MATRIX_PIXEL_FLOW
    #define ENABLE_RGB_MATRIX_PIXEL_RAIN
    #define ENABLE_RGB_MATRIX_STARLIGHT
    #define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
    #define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
    #define ENABLE_RGB_MATRIX_RIVERFLOW

    #ifdef RGB_MATRIX_FRAMEBUFFER_EFFECTS
        #define ENABLE_RGB_MATRIX_TYPING_HEATMAP
        #define ENABLE_RGB_MATRIX_DIGITAL_RAIN
    #endif
    #if defined(RGB_MATRIX_KEYPRESSES) || defined(RGB_MATRIX_KEYRELEASES)
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
        #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
        #define ENABLE_RGB_MATRIX_SPLASH
        #define ENABLE_RGB_MATRIX_MULTISPLASH
        #define ENABLE_RGB_MATRIX_SOLID_SPLASH
        #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
    #endif
#endif
