VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = yes

QMK_SETTINGS = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
MAGIC_ENABLE = yes
SPACE_CADET_ENABLE = yes
WPM_ENABLE = yes
GRAVE_ESC_ENABLE = yes
